baseUrl=https://www.naukri.com/nlogin/login
browser=chrome
headless=true
windowWidth=1366
windowHeight=768
implicitWait=0
explicitWait=20
pageLoadTimeout=45
remote=false
gridUrl=
retry.count=0
screenshots.on.pass=false
screenshots.on.fail=true
screenshots.on.skip=true
pageSource.on.fail=false
browserLogs.on.fail=true
username=
password=
expected.profileName=
expected.mobile=
expected.email=
job.role=SDET
job.location=Bengaluru
expected.jobTitle=Software Development Engineer in Test
