allure.results.directory=reports/allure-results
allure.link.issue.pattern=https://jira.yourorg.com/browse/{}
allure.link.tms.pattern=https://testrail.yourorg.com/index.php?/cases/view/{}
allure.testng.hide.disabled.tests=true
